

import type { SalesManagerLead } from "@/schema/SalesManagerLeadSchema";
export const SalesManagerLeadData: SalesManagerLead[] = [
    {
        "leadId": "LD-001",
        "clientType": "New client",
        "InstrumentType": "instrumental",
        "customerName": "John Smith",
        "customerCompanyName": "ABC Pharmaceuticals Ltd.",
        "customerContactNumber": "9876543210",
        "inquiryLocation": "north",
        "category": "Laboratory Equipment",
        "requirement": "UV-Vis Spectrophotometer for QC Lab",
        "sourceOfLead": "inbound call",
        "salesManager": "Rajesh Kumar",
        "remark": "Urgent requirement for new facility",
        "enquiryStatus": "Call Done",
        "closeRemark": "Negotiating price",
        "companyAddress": "Priya Sharma",
        "technicalFieldEngineer": "Anil Thakur",
        "siteVisit": "Yes",
        "inspectionStatus": "Done",
        "quoteAmount": 450000,
        "quoteAttached": "",
        "attachedPO": "",
        "poDate": "2024-01-15",
        "attachedPI": "",
        "status": true
    },
    {
        "leadId": "LD-002",
        "clientType": "New client",
        "InstrumentType": "chemical",
        "customerName": "Dr. Meera Desai",
        "customerCompanyName": "City Research Institute",
        "customerContactNumber": "8765432109",
        "inquiryLocation": "Bangalore",
        "category": "Research Equipment",
        "requirement": "Compound Microscope for pathology lab",
        "sourceOfLead": "inbound call",
        "salesManager": "Sanjay Verma",
        "remark": "Budget constrained client",
        "enquiryStatus": "Call Pending",
        "closeRemark": "Waiting for budget approval",
        "companyAddress": "Rahul Mehta",
        "technicalFieldEngineer": "Neha Singh",
        "siteVisit": "NO",
        "inspectionStatus": "Pending",
        "quoteAmount": 125000,
        "quoteAttached": "",
        "attachedPO": "",
        "poDate": "",
        "attachedPI": "",
        "status": true
    },
    {
        "leadId": "LD-003",
        "clientType": "Existing client",
        "InstrumentType": "project",
        "customerName": "Mr. Vikram Joshi",
        "customerCompanyName": "State Food Testing Laboratory",
        "customerContactNumber": "7654321098",
        "inquiryLocation": "Delhi",
        "category": "Analytical Instruments",
        "requirement": "Complete HPLC system with accessories",
        "sourceOfLead": "inbound call",
        "salesManager": "Anita Reddy",
        "remark": "Tender based purchase",
        "enquiryStatus": "Call Pending",
        "closeRemark": "Tender in process",
        "companyAddress": "Kiran Nair",
        "technicalFieldEngineer": "Deepak Sharma",
        "siteVisit": "NO",
        "inspectionStatus": "Pending",
        "quoteAmount": 850000,
        "quoteAttached": "",
        "attachedPO": "",
        "poDate": "2024-02-20",
        "attachedPI": "",
        "status": true
    },
    {
        "leadId": "LD-004",
        "clientType": "Existing client",
        "InstrumentType": "instrumental",
        "customerName": "Prof. Arjun Malhotra",
        "customerCompanyName": "University of Science & Technology",
        "customerContactNumber": "6543210987",
        "inquiryLocation": "Chennai",
        "category": "Laboratory Equipment",
        "requirement": "High-speed refrigerated centrifuge",
        "sourceOfLead": "inbound call",
        "salesManager": "Sneha Iyer",
        "remark": "Multiple units required",
        "enquiryStatus": "Call Pending",
        "closeRemark": "Finalizing specifications",
        "companyAddress": "Varun Deshpande",
        "technicalFieldEngineer": "Pooja Gupta",
        "siteVisit": "NO",
        "inspectionStatus": "Pending",
        "quoteAmount": 320000,
        "quoteAttached": "",
        "attachedPO": "",
        "poDate": "2024-01-10",
        "attachedPI": "",
        "status": true
    },
    {
        "leadId": "LD-005",
        "clientType": "Existing client",
        "InstrumentType": "chemical",
        "customerName": "Ms. Anjali Rao",
        "customerCompanyName": "Pure Water Solutions Pvt. Ltd.",
        "customerContactNumber": "5432109876",
        "inquiryLocation": "Hyderabad",
        "category": "Water Testing Equipment",
        "requirement": "Portable pH meters for field testing",
        "sourceOfLead": "inbound call",
        "salesManager": "Mohammed Ali",
        "remark": "Bulk order potential",
        "enquiryStatus": "Call Pending",
        "closeRemark": "Order confirmed",
        "companyAddress": "Sunil Kapoor",
        "technicalFieldEngineer": "Ritu Verma",
        "siteVisit": "NO",
        "inspectionStatus": "Pending",
        "quoteAmount": 75000,
        "quoteAttached": "",
        "attachedPO": "",
        "poDate": "2024-01-08",
        "attachedPI": "",
        "status": true
    },
    {
        "leadId": "LD-006",
        "clientType": "New client",
        "InstrumentType": "instrumental",
        "customerName": "Dr. Sameer Khan",
        "customerCompanyName": "Khan Diagnostic Center",
        "customerContactNumber": "4321098765",
        "inquiryLocation": "Pune",
        "category": "Weighing Instruments",
        "requirement": "Analytical balance for lab",
        "sourceOfLead": "email",
        "salesManager": "Laxmi Nair",
        "remark": "Comparing with competitor products",
        "enquiryStatus": "Warm Lead",
        "closeRemark": "Demo scheduled",
        "companyAddress": "Rajesh Kumar",
        "technicalFieldEngineer": "",
        "siteVisit": "NO",
        "inspectionStatus": "Pending",
        "quoteAmount": 55000,
        "quoteAttached": "",
        "attachedPO": "",
        "poDate": "",
        "attachedPI": "",
        "status": false
    },
    {
        "leadId": "LD-007",
        "clientType": "Existing client",
        "InstrumentType": "project",
        "customerName": "Mr. Robert D'Souza",
        "customerCompanyName": "Mercy General Hospital",
        "customerContactNumber": "3210987654",
        "inquiryLocation": "Kolkata",
        "category": "Sterilization Equipment",
        "requirement": "Large capacity autoclave for operation theater",
        "sourceOfLead": "email",
        "salesManager": "Gautam Sen",
        "remark": "Replacement for old equipment",
        "enquiryStatus": "Hot Lead",
        "closeRemark": "Technical evaluation in progress",
        "companyAddress": "Anil Thakur",
        "technicalFieldEngineer": "Manoj Kumar",
        "siteVisit": "NO",
        "inspectionStatus": "Pending",
        "quoteAmount": 280000,
        "quoteAttached": "",
        "attachedPO": "",
        "poDate": "2024-01-25",
        "attachedPI": "",
        "status": true
    },
    {
        "leadId": "LD-008",
        "clientType": "Existing client",
        "InstrumentType": "instrumental",
        "customerName": "Dr. Nandini Choudhary",
        "customerCompanyName": "National Biological Research Center",
        "customerContactNumber": "2109876543",
        "inquiryLocation": "Ahmedabad",
        "category": "Incubation Equipment",
        "requirement": "CO2 incubator for cell culture",
        "sourceOfLead": "outbound call",
        "salesManager": "Prakash Joshi",
        "remark": "Specific temperature and humidity requirements",
        "enquiryStatus": "New Lead",
        "closeRemark": "Initial discussion",
        "companyAddress": "Rajesh Kumar",
        "technicalFieldEngineer": "",
        "siteVisit": "NO",
        "inspectionStatus": "Pending",
        "quoteAmount": 195000,
        "quoteAttached": "",
        "attachedPO": "",
        "poDate": "",
        "attachedPI": "",
        "status": true
    }
]
